# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: swift-os
description: Bezkompromisowy system dla graczy z maksymalna optymalizacja FPS i RAM

# Wskazujemy oficjalna, bazowa Fedore Kinoite z najnowszym tagiem
base-image: ghcr.io/ublue-os/kinoite
image-version: latest

modules:
  - type: rpm-ostree
    install:
      - chromium
      - steam
      - gamemode
      - gamescope
      - akmod-nvidia
