# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: swift-os
description: Bezkompromisowy system dla graczy z maksymalna optymalizacja FPS i RAM

# Najpotężniejsza, gotowa baza gamingowa od Universal Blue
base-image: ghcr.io/ublue-os/kinoite-nvidia
image-version: latest
