# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: swift-os
description: Bezkompromisowy system dla graczy z maksymalna optymalizacja FPS i RAM

# Bierzemy oficjalny, certyfikowany obraz bezpośrednio od Fedory (wydanie stabilne 40)
base-image: oci.fedoraproject.org/fedora-iot/kinoite
image-version: 40

modules:
  - type: rpm-ostree
    install:
      - chromium
      - steam
      - gamemode
      - gamescope
      - akmod-nvidia
