name: Build SwiftOS
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  bluebuild:
    name: Build SwiftOS
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Build Custom Image
        uses: blue-build/github-action@v1
        with:
          recipe: 'recipe.yml'
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
